export type ProjectType =
  | "sale"
  | "purchase"
  | "rental"
  | "subscription"
  | "service"
  | "consulting"
  | "maintenance"
  | "upgrade"
  | "renewal"
  | "refund"
  | "exchange"
  | "trial"
  | "lead"
  | "follow_up";
